# https://travis-ci.org/jschneier/django-storages/
sudo: false
language: python

cache: pip

matrix:
  fast_finish: true
  include:
    - env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.4
      env: TOXENV=py34-django111
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.4
      env: TOXENV=py34-django20
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.5
      env: TOXENV=py35-djangomaster
    - python: 3.6
      env: TOXENV=py36-djangomaster
  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox

script:
  - tox
