language: python

env:
  - TOX_ENV=py26-django15
  - TOX_ENV=py26-django16
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py32-django15
  - TOX_ENV=py32-django16
  - TOX_ENV=py32-django17
  - TOX_ENV=py33-django15
  - TOX_ENV=py33-django16
  - TOX_ENV=py33-django17
  - TOX_ENV=py34-django15
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

